# Generated by Django 3.2.6 on 2021-08-12 18:37
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id', models.CharField(
                        max_length=35,
                        primary_key=True, serialize=False,
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                (
                    'user', models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user',
                    ),
                ),
            ],
        ),
    ]
