version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    ports:
      - "5433:5432"
    networks:
      - net
    restart: unless-stopped
  blogpost:
    build:
      context: ./
      dockerfile: blogpost.dockerfile
    container_name: blogpost
    restart: always
    depends_on:
      - "postgres"
    ports:
      - '8000:8000'
    networks: 
      - net
networks:
  net:
    name: blogpost