# Generated by Django 3.2.6 on 2021-08-12 18:37
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id', models.CharField(
                        max_length=35,
                        primary_key=True, serialize=False,
                    ),
                ),
                ('displayName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
